name: Merge Dependabot PRs

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  check-lint-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check lint job status
        id: check-status
        run: |
          # Use GitHub API to check the status of your lint job
          # This is just a pseudo-code snippet; you'll need to implement this in a way that matches your actual setup
          LINT_STATUS=$(curl -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/your-repo/actions/runs?event=pull_request | jq '.workflow_runs[] | select(.name=="Lint Code and Dockerfiles") | .conclusion')
          if [[ $LINT_STATUS == "success" ]]; then
            echo "Lint job successful. Proceeding with merge."
          else
            echo "Lint job failed. Exiting."
            exit 1
          fi
          
  merge-me:
    needs: check-lint-status
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRESET: DEPENDABOT_PATCH
